const bcrypt = require("bcryptjs");
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

// const hashPassword = bcrypt.hashSync("123456", 10);

// const userData = [
//   {
//     firstName: "LEO",
//     lastName: "LAPTANSUPAPON",
//     password: hashPassword,
//     email: "test01@gmail.com",
//     phone: "1111111111",
//   },
//   {
//     firstName: "LEO",
//     lastName: "LAPTANSUPAPON",
//     password: hashPassword,
//     email: "test02@gmail.com",
//     phone: "1111111111",
//   },
//   {
//     firstName: "LEO",
//     lastName: "LAPTANSUPAPON",
//     password: hashPassword,
//     email: "test03@gmail.com",
//     phone: "1111111111",
//   },
//   {
//     firstName: "LEO",
//     lastName: "LAPTANSUPAPON",
//     password: hashPassword,
//     email: "test04@gmail.com",
//     phone: "1111111111",
//   },
//   {
//     firstName: "LEO",
//     lastName: "LAPTANSUPAPON",
//     password: hashPassword,
//     email: "test05@gmail.com",
//     phone: "1111111111",
//   },
//   {
//     firstName: "LEO",
//     lastName: "LAPTANSUPAPON",
//     password: hashPassword,
//     email: "test06@gmail.com",
//     phone: "1111111111",
//   },
//   {
//     firstName: "LEO",
//     lastName: "LAPTANSUPAPON",
//     password: hashPassword,
//     email: "test07@gmail.com",
//     phone: "1111111111",
//   },
//   {
//     firstName: "LEO",
//     lastName: "LAPTANSUPAPON",
//     password: hashPassword,
//     email: "test08@gmail.com",
//     phone: "1111111111",
//   },
// ];

const bookData = [
  {
    title: "Let boy blood you.",
    description:
      "Get letter material reason Mr program word peace. Three firm baby career.",
    author: "Gregory Russell",
    price: 10.0,
    publisher: "Chang, Brooks and Williams",
    publishDate: "11-2021",
    amount: 46,
    categoryId: 1,
    image: "https://dummyimage.com/396x483",
  },
  {
    title: "Wait specific reduce.",
    description:
      "Deep baby so figure fish thus. Sit particular only boy site. Reality strong moment safe act section. Cell more picture visit state strong.",
    author: "Gregory Martin",
    price: 39.14,
    publisher: "Turner, Mcneil and Bennett",
    publishDate: "08-2024",
    amount: 30,
    categoryId: 1,
    image: "https://placekitten.com/1017/758",
  },
  {
    title: "Region claim have.",
    description:
      "Available hour strategy any employee. Center dark effect practice. Fill our least environment. Bar forward little without.",
    author: "Willie Roberts",
    price: 45.08,
    publisher: "Acosta Ltd",
    publishDate: "10-2019",
    amount: 90,
    categoryId: 1,
    image: "https://placekitten.com/957/443",
  },
  {
    title: "Appear environmental add help.",
    description:
      "Bill whether make age exactly condition truth. Really happen democratic interview fear.",
    author: "Lee Smith",
    price: 29.25,
    publisher: "Mejia Ltd",
    publishDate: "11-2019",
    amount: 50,
    categoryId: 1,
    image: "https://www.lorempixel.com/375/290",
  },
  {
    title: "Organization carry term say.",
    description:
      "Film interest it local. Consider we far western increase plan concern second. Open power item market time within.",
    author: "Terry Anderson",
    price: 33.91,
    publisher: "Mcgee-Hawkins",
    publishDate: "09-2022",
    amount: 7,
    categoryId: 1,
    image: "https://placekitten.com/408/597",
  },
  {
    title: "Main throughout.",
    description:
      "Environmental citizen green list often. Become look medical later business second nothing. Bank like possible see sport.",
    author: "Grant Henry",
    price: 46.73,
    publisher: "Gomez, Ford and Little",
    publishDate: "05-2024",
    amount: 12,
    categoryId: 2,
    image: "https://placeimg.com/425/561/any",
  },
  {
    title: "Former chair wish must two.",
    description:
      "Indicate star a home capital white room amount. Worry president hundred system sit opportunity amount. Move role plan knowledge.",
    author: "Matthew Wood",
    price: 20.44,
    publisher: "Johnson LLC",
    publishDate: "03-2024",
    amount: 24,
    categoryId: 1,
    image: "https://placeimg.com/368/905/any",
  },
  {
    title: "Miss film ground.",
    description:
      "Themselves name media customer suffer. Other different simply five. Easy group maybe action.",
    author: "Krystal Hardin",
    price: 31.41,
    publisher: "Bailey-Oliver",
    publishDate: "12-2021",
    amount: 44,
    categoryId: 1,
    image: "https://www.lorempixel.com/891/733",
  },
  {
    title: "Certain clear pass reveal.",
    description:
      "System recent television speech. Everything control spend party idea.",
    author: "Mallory Hicks",
    price: 6.74,
    publisher: "Osborne PLC",
    publishDate: "07-2024",
    amount: 12,
    categoryId: 2,
    image: "https://placeimg.com/39/378/any",
  },
  {
    title: "Relationship four always.",
    description:
      "Staff positive mother movie. Give result be. Tend enjoy allow edge.",
    author: "Christopher Hobbs",
    price: 48.24,
    publisher: "Cain, Saunders and Larson",
    publishDate: "05-2021",
    amount: 13,
    categoryId: 1,
    image: "https://dummyimage.com/125x681",
  },
  {
    title: "Mouth force why movie soon.",
    description:
      "Week series budget none believe political rich. Middle part issue trouble event local truth floor. Use response drop include one word growth.",
    author: "Ivan Anderson",
    price: 44.64,
    publisher: "Meyer-Chavez",
    publishDate: "04-2022",
    amount: 83,
    categoryId: 2,
    image: "https://www.lorempixel.com/621/431",
  },
  {
    title: "Never century.",
    description:
      "Bad from today though level. Ball put foreign. Analysis approach respond through do physical sing.",
    author: "Heather Long",
    price: 19.53,
    publisher: "White Group",
    publishDate: "05-2022",
    amount: 22,
    categoryId: 1,
    image: "https://www.lorempixel.com/874/944",
  },
  {
    title: "Capital light.",
    description:
      "Blood us far difficult. College child before wrong. Detail room record where.",
    author: "Gregory Wilson",
    price: 8.51,
    publisher: "Estrada, Jones and Faulkner",
    publishDate: "06-2024",
    amount: 7,
    categoryId: 1,
    image: "https://placekitten.com/469/29",
  },
  {
    title: "Bank speech me.",
    description:
      "Price energy political student speech too place. Enjoy mention increase nearly later. Choice cell dog.",
    author: "Darrell Dunn",
    price: 14.64,
    publisher: "Mccormick and Sons",
    publishDate: "08-2022",
    amount: 24,
    categoryId: 1,
    image: "https://placekitten.com/142/242",
  },
  {
    title: "Over night only art subject.",
    description:
      "Kind above toward after throughout across could. Size we customer under including. Big reality type.",
    author: "Rebecca Hart",
    price: 46.1,
    publisher: "Lee-Harding",
    publishDate: "04-2022",
    amount: 1,
    categoryId: 1,
    image: "https://dummyimage.com/377x1005",
  },
  {
    title: "Person anyone one likely organization.",
    description:
      "Member bit charge doctor system economic. Character per leave.",
    author: "Steven Villa",
    price: 46.48,
    publisher: "Smith, Mitchell and Moon",
    publishDate: "04-2023",
    amount: 40,
    categoryId: 2,
    image: "https://dummyimage.com/906x965",
  },
  {
    title: "Enjoy bill long.",
    description:
      "Live stuff size represent book. Thank speech bill style. Level environmental state world effort medical site.",
    author: "Patrick Garcia",
    price: 20.74,
    publisher: "Brown Inc",
    publishDate: "06-2022",
    amount: 78,
    categoryId: 1,
    image: "https://placeimg.com/639/946/any",
  },
  {
    title: "Vote we.",
    description: "Top choose attack institution. Environmental author music.",
    author: "Samuel Hernandez",
    price: 7.29,
    publisher: "Williams-Martinez",
    publishDate: "05-2023",
    amount: 67,
    categoryId: 2,
    image: "https://placekitten.com/513/886",
  },
  {
    title: "Fill amount.",
    description:
      "Soldier under method usually whom. New forward industry walk vote. Strategy if medical positive evidence.",
    author: "Amber Smith",
    price: 37.6,
    publisher: "Haas Ltd",
    publishDate: "12-2023",
    amount: 3,
    categoryId: 1,
    image: "https://placekitten.com/566/30",
  },
  {
    title: "Reveal policy.",
    description:
      "Response born wonder water agency race deep. Better view forget suffer new.",
    author: "Andrea Powell",
    price: 48.7,
    publisher: "Kim-Sloan",
    publishDate: "01-2023",
    amount: 33,
    categoryId: 2,
    image: "https://placeimg.com/744/855/any",
  },
  {
    title: "Week as bill hospital evening.",
    description:
      "Southern feel price course civil several. Deep rather activity born professor nature traditional. Hotel standard indicate fill.",
    author: "Jessica Tran",
    price: 12.6,
    publisher: "Larsen, Green and Nguyen",
    publishDate: "01-2023",
    amount: 40,
    categoryId: 1,
    image: "https://placeimg.com/838/253/any",
  },
  {
    title: "Fast happy second.",
    description: "Wear east Democrat manage.",
    author: "Christina Simmons DDS",
    price: 38.78,
    publisher: "Lang, Brown and Herrera",
    publishDate: "02-2023",
    amount: 13,
    categoryId: 1,
    image: "https://placekitten.com/285/625",
  },
  {
    title: "Budget already.",
    description:
      "Season fire usually happen myself recently. Simple record seem customer nation him film. Me other tax range. Responsibility reality letter themselves young information.",
    author: "Robert Woods",
    price: 18.16,
    publisher: "Jones and Sons",
    publishDate: "01-2024",
    amount: 12,
    categoryId: 2,
    image: "https://placeimg.com/691/650/any",
  },
  {
    title: "Economy mission get.",
    description:
      "Window set usually. Probably run clear trial. Sea employee image window ago bank.",
    author: "Rick Williams",
    price: 22.51,
    publisher: "Glenn-Curry",
    publishDate: "11-2020",
    amount: 20,
    categoryId: 1,
    image: "https://dummyimage.com/769x630",
  },
  {
    title: "Perhaps east him black card.",
    description:
      "Religious tell look school now firm hospital. Argue summer heavy research radio meeting. Wind every cup change present southern series.",
    author: "Dustin Lyons",
    price: 41.01,
    publisher: "Duke, Hoffman and Robles",
    publishDate: "02-2021",
    amount: 42,
    categoryId: 1,
    image: "https://placekitten.com/1006/50",
  },
  {
    title: "Attorney itself power.",
    description:
      "Only market game game bag. Side become performance sea drug different list.",
    author: "Amber Wells",
    price: 17.41,
    publisher: "Gomez-Ramos",
    publishDate: "08-2022",
    amount: 38,
    categoryId: 1,
    image: "https://dummyimage.com/324x758",
  },
  {
    title: "Laugh able purpose think.",
    description:
      "Her mind while top affect war analysis. Education measure according fire. White research voice tend whatever.",
    author: "Melissa Flynn",
    price: 13.29,
    publisher: "Bennett, Baldwin and Clay",
    publishDate: "09-2023",
    amount: 15,
    categoryId: 1,
    image: "https://www.lorempixel.com/39/778",
  },
  {
    title: "Environmental stay.",
    description:
      "Save concern policy book social piece work open. Go product suffer decade floor. Forget health anyone.",
    author: "Matthew Day",
    price: 48.58,
    publisher: "Jacobs-Guzman",
    publishDate: "01-2022",
    amount: 58,
    categoryId: 2,
    image: "https://www.lorempixel.com/786/975",
  },
  {
    title: "Note cup everyone article few.",
    description:
      "Quite election education trade majority marriage able. Rate big charge break act foreign.",
    author: "Scott Medina",
    price: 29.36,
    publisher: "Knight-Jones",
    publishDate: "08-2021",
    amount: 85,
    categoryId: 1,
    image: "https://dummyimage.com/909x612",
  },
  {
    title: "Shoulder particular our.",
    description: "Movement suddenly she receive sign head.",
    author: "Elizabeth Tate",
    price: 22.39,
    publisher: "Trujillo Group",
    publishDate: "01-2022",
    amount: 22,
    categoryId: 1,
    image: "https://placeimg.com/236/429/any",
  },
  {
    title: "Weight group.",
    description:
      "Account population among even nor practice pick. Create current official imagine know toward place.",
    author: "Laurie Callahan",
    price: 23.2,
    publisher: "Woodard-Mclaughlin",
    publishDate: "02-2024",
    amount: 88,
    categoryId: 2,
    image: "https://placekitten.com/110/748",
  },
  {
    title: "Present behavior story similar.",
    description:
      "White professor security quality lawyer. Point lead contain six inside stop.",
    author: "Jeffrey Henry",
    price: 43.13,
    publisher: "Shelton, Merritt and Sanchez",
    publishDate: "07-2024",
    amount: 24,
    categoryId: 1,
    image: "https://placeimg.com/70/786/any",
  },
  {
    title: "Social economy meet.",
    description:
      "Pattern option work home. Would treat poor available top here. Star TV fall avoid only.",
    author: "John Harris",
    price: 23.4,
    publisher: "Jacobs and Sons",
    publishDate: "03-2021",
    amount: 37,
    categoryId: 2,
    image: "https://dummyimage.com/406x223",
  },
  {
    title: "Section stock.",
    description:
      "Cell national also example begin institution society. Current follow book human dog responsibility. Teach then box such.",
    author: "Carla Murphy",
    price: 37.81,
    publisher: "David-Lewis",
    publishDate: "01-2020",
    amount: 88,
    categoryId: 1,
    image: "https://www.lorempixel.com/115/676",
  },
  {
    title: "Commercial program direction employee choice.",
    description:
      "East government senior. Memory threat seat now own miss. Report study trial science provide try.",
    author: "Donna Barnett",
    price: 10.98,
    publisher: "Gamble, Padilla and Reyes",
    publishDate: "06-2022",
    amount: 98,
    categoryId: 2,
    image: "https://placeimg.com/230/402/any",
  },
  {
    title: "Blood system recent really.",
    description: "Wall region table truth sense. Suddenly building space goal.",
    author: "Vincent Ware",
    price: 7.5,
    publisher: "Patel-Fisher",
    publishDate: "04-2024",
    amount: 6,
    categoryId: 1,
    image: "https://dummyimage.com/696x401",
  },
  {
    title: "Fine production manage lead one.",
    description: "Hope plant safe. Task series country but.",
    author: "Jill Johnson",
    price: 32.21,
    publisher: "Johnson, Williams and Larson",
    publishDate: "02-2020",
    amount: 56,
    categoryId: 1,
    image: "https://placekitten.com/166/630",
  },
  {
    title: "Beat skill else.",
    description:
      "Research out in ability few senior along measure. Trade four difference west word few. Production because training professor.",
    author: "Sandra Hughes",
    price: 11.04,
    publisher: "Mclean Ltd",
    publishDate: "02-2024",
    amount: 32,
    categoryId: 2,
    image: "https://placeimg.com/1009/694/any",
  },
  {
    title: "Market high near decision also.",
    description:
      "To skill already hour whom. In program head. Least child local.",
    author: "Andrea Blake",
    price: 38.73,
    publisher: "Sawyer, Hamilton and Roberts",
    publishDate: "02-2020",
    amount: 94,
    categoryId: 1,
    image: "https://dummyimage.com/898x735",
  },
  {
    title: "Call I show.",
    description:
      "Season we student door out. Garden nature thousand speak step better who.",
    author: "Nicole Avery",
    price: 9.99,
    publisher: "Lewis, Mitchell and Serrano",
    publishDate: "02-2020",
    amount: 52,
    categoryId: 1,
    image: "https://placekitten.com/180/359",
  },
  {
    title: "Glass field artist.",
    description:
      "Couple executive size your a president. Before resource toward really truth section speak. Not wrong reach view continue.",
    author: "Megan White",
    price: 20.66,
    publisher: "Hardy Inc",
    publishDate: "11-2019",
    amount: 17,
    categoryId: 2,
    image: "https://placekitten.com/544/590",
  },
  {
    title: "Manage school marriage full.",
    description: "Project inside treat style executive most.",
    author: "Erica Mccullough",
    price: 24.08,
    publisher: "Dudley Ltd",
    publishDate: "09-2022",
    amount: 90,
    categoryId: 2,
    image: "https://www.lorempixel.com/963/257",
  },
  {
    title: "Campaign life country.",
    description:
      "Type camera month term case old population. Modern often research last become.",
    author: "Deborah Rogers",
    price: 32.48,
    publisher: "Mullins-Kelly",
    publishDate: "08-2022",
    amount: 10,
    categoryId: 1,
    image: "https://placeimg.com/775/564/any",
  },
  {
    title: "The service much.",
    description: "Lose wife building available all ground energy matter.",
    author: "Paul Turner",
    price: 42.51,
    publisher: "Davis LLC",
    publishDate: "06-2020",
    amount: 22,
    categoryId: 1,
    image: "https://www.lorempixel.com/51/632",
  },
  {
    title: "Cell increase degree eight can.",
    description:
      "Different picture whom since. Camera under bag son measure change.",
    author: "Megan Mcgee",
    price: 24.54,
    publisher: "Hunter, Clark and Hernandez",
    publishDate: "09-2021",
    amount: 54,
    categoryId: 2,
    image: "https://placekitten.com/348/877",
  },
  {
    title: "Item rule though several action.",
    description:
      "Traditional pay poor message nearly red nation. Purpose debate summer provide rise.",
    author: "James Ramos DVM",
    price: 45.45,
    publisher: "Hicks, Lee and Gardner",
    publishDate: "09-2021",
    amount: 66,
    categoryId: 1,
    image: "https://placeimg.com/868/409/any",
  },
  {
    title: "Reason effect like.",
    description:
      "Per business police foot head matter what. Conference set teach many leg word. Network expert body machine relationship hotel really.",
    author: "Emily Mitchell",
    price: 14.3,
    publisher: "Cantrell, Williams and Sharp",
    publishDate: "08-2022",
    amount: 34,
    categoryId: 1,
    image: "https://placekitten.com/837/976",
  },
  {
    title: "Reason believe especially during major.",
    description:
      "Floor piece though. Home white rise sing difference. Debate her upon rate respond of.",
    author: "Brittney Miller",
    price: 17.79,
    publisher: "Robinson Inc",
    publishDate: "01-2021",
    amount: 59,
    categoryId: 2,
    image: "https://placeimg.com/488/864/any",
  },
  {
    title: "Enjoy or foot idea college.",
    description:
      "Woman concern individual candidate game. Adult why similar lawyer energy station.",
    author: "Melanie Cunningham",
    price: 48.47,
    publisher: "Jordan, Walker and Smith",
    publishDate: "06-2022",
    amount: 80,
    categoryId: 1,
    image: "https://placeimg.com/925/245/any",
  },
  {
    title: "Reveal society goal.",
    description:
      "Half wrong another little buy inside civil. Why left check vote respond leg. Federal bag say national cost resource.",
    author: "Jeremy Murphy",
    price: 24.02,
    publisher: "Carter, Smith and Simpson",
    publishDate: "04-2022",
    amount: 11,
    categoryId: 1,
    image: "https://placeimg.com/709/470/any",
  },
  {
    title: "Game believe threat speak.",
    description:
      "Visit among occur. Child should writer create simple. No tend no.",
    author: "Shelby Wilson",
    price: 16.24,
    publisher: "Brewer-Alvarado",
    publishDate: "08-2023",
    amount: 12,
    categoryId: 2,
    image: "https://placekitten.com/77/93",
  },
  {
    title: "Newspaper budget power majority.",
    description:
      "Shoulder people son late book. International approach season begin.",
    author: "Michelle Clark",
    price: 43.75,
    publisher: "Sloan-Carpenter",
    publishDate: "08-2021",
    amount: 41,
    categoryId: 2,
    image: "https://placeimg.com/41/37/any",
  },
  {
    title: "Out why discover task.",
    description: "Human office become street.",
    author: "Kaitlyn Stone",
    price: 9.0,
    publisher: "Jones Inc",
    publishDate: "01-2023",
    amount: 29,
    categoryId: 2,
    image: "https://placeimg.com/414/187/any",
  },
  {
    title: "Answer this point.",
    description:
      "After deal together information night nothing. Send security old report.",
    author: "Alex Roy MD",
    price: 30.53,
    publisher: "Maxwell, Huynh and Reed",
    publishDate: "07-2023",
    amount: 6,
    categoryId: 1,
    image: "https://dummyimage.com/237x804",
  },
  {
    title: "Protect suddenly seat.",
    description:
      "Perform experience analysis place run. Type report with skill contain.",
    author: "Benjamin Mann",
    price: 31.21,
    publisher: "Gardner, Brady and Meyer",
    publishDate: "07-2022",
    amount: 46,
    categoryId: 2,
    image: "https://placekitten.com/575/403",
  },
  {
    title: "With common voice matter.",
    description:
      "Stage collection research clearly its. Culture people likely poor daughter daughter. Life term accept quite art.",
    author: "Bridget Matthews",
    price: 9.71,
    publisher: "Coleman-Norris",
    publishDate: "03-2021",
    amount: 59,
    categoryId: 2,
    image: "https://dummyimage.com/811x542",
  },
  {
    title: "Friend hundred.",
    description:
      "Lot project interesting quite stand fire imagine. Wonder lead pass return.",
    author: "Linda Munoz",
    price: 48.52,
    publisher: "Hayes-Jones",
    publishDate: "04-2023",
    amount: 76,
    categoryId: 1,
    image: "https://www.lorempixel.com/526/740",
  },
];

console.log("DB seed...");

async function run() {
  //   await prisma.user.createMany({
  //     data: userData,
  //   });

  await prisma.product.createMany({
    data: bookData,
  });
}

run();
